name: Calculator CI/CD Pipeline

permissions:
  contents: read
  actions: read
  checks: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r BE/requirements.txt
        # Install testing dependencies
        pip install pytest requests
        # Install generated client dependencies
        pip install httpx attrs typing-extensions python-dateutil
    
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=." >> $GITHUB_ENV
    
    - name: Start REST API in background
      run: |
        cd BE && python calculator.py --rest --port 5001 &
        sleep 10
        curl -f http://localhost:5001/docs || curl -f http://localhost:5001/ || echo "API starting..."
    
    - name: Run tests
      run: pytest --junit-xml=report.xml
    
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: pytest
        path: report.xml
        reporter: java-junit

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: judevops.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build -t judevops.azurecr.io/yahia_alali-calculator ./BE
        docker push judevops.azurecr.io/yahia_alali-calculator
